# Use container based infrastructure
sudo: false

language: python

addons:
  apt:
    packages:
    - imagemagick

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install --quiet -r requirements.txt
  # Separate the coveralls package because it is only a test requirement
  - pip install --quiet coveralls

script:
  - nosetests --with-coverage --cover-package=legofy
  - python setup.py install
  - legofy legofy/assets/flower.jpg flower_lego.png
  - legofy --palette all legofy/assets/flower.jpg flower_lego_all.png

after_success:
  - coveralls
